development:
  adapter: postgresql
  encoding: unicode
  database: projects_development_master
  pool: 5
  username: kellywaters
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: projects_test_master
  pool: 5
  username: kellywaters
  password: 